### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ytbeom** [ytbeom/bucket-list-bingo#1]
### Home
- [x] string to json
- [x] check json and set state
- [x] Users to selectBox
- [x] navigate with id from selectBox data
- [x] 제목 정하고 위치 정하기
- [x] 배경 꾸미기 with Emoji
- [x] select CSS 작업

### BingoViewer
- [x] pathParam 가지고 GET API 호출
- [x] GET API 결과물로 set state
- [x] state로 화면 그리기
- [x] 칸 클릭하면 팝업 띄우기 + dimmer
- [x] 팝업에 내용 / 완료로 표시 / 미완료로 표시 버튼 넣기
- [x] 완료로 표시 / 미완료로 표시 버튼에 POST API 연결 및 다시 GET 해오는 API까지 붙이기
- [x] 완료 / 미완료 CSS
- [x] 빙고 여부 체크 함수 생성
- [x] 팝업 content CSS

### Aggregation
- [x] Notion Database 생성 (사용자, 번호, 위치, 내용, 완료여부)
- [x] Notion API + AWS Lambda 세팅
- [x] GitHub Pages 배포 및 테스트
- [x] API 주소 숨길 방법 없을지 고민해보기

### Very Simple Login Prompt
- [x] 비밀번호 쳐야 들어올 수 있게 만들기
- [x] 비밀번호 sessionStorage에 저장하기
